#!/bin/bash
#

wget https://storage.googleapis.com/deep-learning-lib/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb
wget https://storage.googleapis.com/deep-learning-lib/cuda-repo-ubuntu1604-8-0-local-cublas-performance-update_8.0.61-1_amd64.deb
wget https://storage.googleapis.com/deep-learning-lib/libcudnn6_6.0.21-1%2Bcuda8.0_amd64.deb
wget https://storage.googleapis.com/deep-learning-lib/libcudnn6-dev_6.0.21-1%2Bcuda8.0_amd64.deb
#wget https://storage.googleapis.com/deep-learning-lib/libcudnn7_7.0.3.11-1%2Bcuda8.0_amd64.deb
#wget https://storage.googleapis.com/deep-learning-lib/libcudnn7-dev_7.0.3.11-1%2Bcuda8.0_amd64.deb

sudo dpkg -i cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb
sudo apt-get update && sudo apt-get install cuda -y
sudo dpkg -i cuda-repo-ubuntu1604-8-0-local-cublas-performance-update_8.0.61-1_amd64.deb

sudo dpkg -i libcudnn6_6.0.21-1%2Bcuda8.0_amd64.deb
sudo dpkg -i libcudnn6-dev_6.0.21-1%2Bcuda8.0_amd64.deb
