#!/bin/bash
cat <<LIST > /etc/apt/sources.list.d/jonathonf-ubuntu-python-3_6-xenial.list
deb http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial main
# deb-src http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial main
LIST

add-apt-repository ppa:jonathonf/python-3.6 -y
add-apt-repository ppa:gstreamer-developers/ppa -y

apt-get update
apt-get install -y python3.6-dev python3.6
apt-get install -y \
        build-essential \
        cmake \
        git \
        wget \
        unzip \
        yasm \
        python-apt \
        pkg-config \
        gstreamer1.0* \
    	libblas-dev \
	    liblapack-dev \
        libswscale-dev \
        libeigen3-dev \
	    libcupti-dev \
        libtbb2 \
        libtbb-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libjasper-dev \
        libavformat-dev \
        libpq-dev \
        libboost-all-dev \
        libgtk2.0-dev
